### ISSUE TITLE
Pivot Table Box Plots

### ISSUE THREAD

**Issue by kjans123** [plotly/dash-pivottable#34]
Would it be possible to get box plots in the list of displayable analyses?

**Comment by xhlulu** [comment]
Hi @kjans123 it's an interesting idea, but it's not something built-in for the original `react-pivottable` library. If you think it's something worth adding, feel free to open a PR in the [react-pivottable repo](https://github.com/plotly/react-pivottable) and once it's merged and released, we can update dash-pivottable to include the new option.
